### ISSUE TITLE
FH Character sheets do not save/show edits, loot deck breaks game/disconnects clients

### ISSUE THREAD

**Issue by z-m-k** [Lurkars/gloomhavensecretariat#101]
- [ ] FH char sheets cannot be edited (adding items is not always working, adjusting gold is not working, adjusting tick marks/battleGoals is not working, loot is not working). Editing `ghs-game.json` solves some of these issues (battelGoals are reflected, items are reflected, gold is reflected). But not others: loot is not reflected, but is present in subsequent exports.
- [ ] Using loot deck during game while connected to a ghs-server is not syncing with the server/disconnects clients after loot other than coins is drawn. After state `X`,  when you draw loot and you draw something other than a coin, the client will reflect the drawn items and you can continue playing (possibly for some few rounds) until state `X+Y`. However, after refreshing the page or reconnecting to the server manually/automatically the game is restored to state `X` and all progress is lost. Easiest to replicate is to start a new FH scenario and loot once. Failing a scenario with loot items results in no gold/loot items being saved.

[ghs-game.zip](https://github.com/Lurkars/gloomhavensecretariat/files/10566793/ghs-game.zip)

**Comment by Lurkars** [comment]
The first one is actual bug on server component. I created a fix, should already be deployed. (Problem was, that server stored data with UPPERCASE, then got errors with having keys "money" and "MONEY" for example). 

I am pretty sure that this issue leads to the second problem, because I was not able to reproduce this with the fix. And because of first problem, server just didn't sync right, because not accepting data or not sending updates to clients.

Please verify fix!

**Comment by Lurkars** [comment]
Ah and short hint, if you have a local game state, press F5 and lost some data. You should always be able to use the undo function to get at least a state 1 step before.

**Comment by z-m-k** [comment]
Yes. The fix to 1) fixed the 2) as well :)

I know about the workaround with going back.
