### ISSUE TITLE
Shield values do not stack when Add stats values is checked

### ISSUE THREAD

**Issue by pikdonker** [Lurkars/gloomhavensecretariat#112]
First of all: Thanks for this great app!

Second: Shield values stack according to the rules, but this does not seem to be implemented properly. Example:
![image](https://user-images.githubusercontent.com/58171422/216814257-48a174cd-d9b5-4188-b46c-7ef0f6a25f4c.png)

This should read Shield 2 instead of 1, because I have the setting Add stats values to abilities checked. Fwiw, good old Gloomhaven Helper did stack shield values in cases like this.

**Comment by Lurkars** [comment]
Hey, you may start a discussion on that, but this is on purpose. I have a full calculated shield value added to the standee menu to see the real shield (and also retaliate) when open standee menu to lower HP.

I only know, that old helper has a issue here, because like in your example GHH always would show shield 2 even before city guards turn, which is wrong, because before it's turn CG should only have 1 shield from stats. 

And I made the decision, that reflecting that directly on the card may be confusing.

**Comment by Lurkars** [comment]
Okay have thought about it now a bit, and I think you're right. You need to know that the shield on the card applies after turn anyway. So showing the full calculated shield value here is correct. I will change this (and also for retaliate).

**Comment by Lurkars** [comment]
Please review changes in [v0.43.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.43.7).

**Comment by pikdonker** [comment]
That was quick, thanks!

Don't think we noticed the stacked shield value in the standee menu, if we had I probably wouldn't have opened this issue.. Although I think the solution you've gone for now really is better, so thanks again!
