### ISSUE TITLE
Hazardous Terrain costs different in Frosthaven

### ISSUE THREAD

**Issue by farling42** [Lurkars/gloomhavensecretariat#127]
When playing a frosthaven scenario, the displayed hazardous terrain costs are wrong.

It is one of the marked changes between Gloomhaven and Frosthaven.

**Comment by Lurkars** [comment]
Can you provide example? Because I already implement the different calculation for FH. So if not shown, this is not missing but a bug!

**Comment by Lurkars** [comment]
Haha okay, it's a bug. I revertet the roles. So for FH I apply old rules and for all other editions now the FH rules. Thanks for noticing! Will be fixed today!

**Comment by farling42** [comment]
Do the "Always Use" settings need to be enabled if you already have Game Management set to only show Frosthaven (and have Frosthaven selected in the "Set Edition" menu)?

**Comment by Lurkars** [comment]
> Do the "Always Use" settings need to be enabled if you already have Game Management set to only show Frosthaven (and have Frosthaven selected in the "Set Edition" menu)?

No, when edition is set to Frosthaven, it will apply automatically. The issue is simple, see
https://github.com/Lurkars/gloomhavensecretariat/blob/main/src/app/game/businesslogic/LevelManager.ts#L53
I check for FH rules or always, and then apply old rules, otherwise apply new rules. It must just be switched. FH rules apply when edition is set to FH or no edition is set, but FH scenarios is played!

**Comment by farling42** [comment]
Yes, this is working correctly in 0.45.4
