### ISSUE TITLE
When putting aside a character, all stats are lost

### ISSUE THREAD

**Issue by farling42** [Lurkars/gloomhavensecretariat#128]
When I removed a character (Banner Spear) from the party due to switching to a different one (Drifter), on going back to the first character (Banner Spear) it was entered as a 1 level character rather than retaining the information about that character from when it was last in the party.

The Frosthaven rules talk about "putting aside" a character to play again later, rather than only abandoning them.

**Comment by Lurkars** [comment]
Removing a character will remove it! I have added a absent feature, which can be used for this: click on the charterers name in figure status menu or on character sheet to toggle absent state. With setting "hide absent figures" you can also hide those characters in list!

**Comment by farling42** [comment]
I've removed the spoiler information from my example characters.

**Comment by Lurkars** [comment]
It's in the FAQ and mainly for the purpose of player missing on a session (therefore absent...) I didn't know there is also a game mechanic actually require this! Will think about changing it, but yeah, many stuff is more or less a bit hidden because I wont to not spam up the well done old helper UX and not add to much stuff on character sheet and so on. I think I need to do more like a tutorial mode where every function is explained or so.

**Comment by farling42** [comment]
On page 65 in the "Create a Character" section (second paragraph), it says that a player can set aside a character if they want to play something else for a while. When set aside all the personal quest, items, gold and resources are all kept.

**Comment by Lurkars** [comment]
I added icons next to name to indicate that feature more.

**Comment by farling42** [comment]
Excellent. I like the Absent/Present icons. :-)
