### ISSUE TITLE
Doesn't work on iOS 12.5.7

### ISSUE THREAD

**Issue by mherodev** [Lurkars/gloomhavensecretariat#172]
My wife got me an iPad for my birthday to use with this app (so she could continue using her iPad while we play), but tragically it just whitescreens when it loads in both Safari and Chrome.

The iPad is pretty old admittedly, so perhaps it just becomes a toy for our kid, but it'd be great if it worked for its intended purpose 😅

Thanks!
Michael

**Comment by Lurkars** [comment]
Hello, first of all I have no Apple device, so on general support of iOS and MacOS my experience totally depends on user feedback. I know about an issue with not closing pop-up menus solved with updating iOS/Safari. So this was a device with an older version already got more than a white screen. So I think, if you're not able to update, the device is just out of support.

Also I can tell you from my knowledge, that a different browser won't make any difference on iOS, because every browser has to use the Safari engine to render, so technically every other browser like Chrome for example is just a Safari browser with different look and feel.

Since I am using Angular Framework, looking at their [support page] (https://angular.io/guide/browser-support) only the *2 most recent major versions* are supported.

**Comment by UChess1986** [comment]
This does sounds like a "iPad is too old" issue, for the record I have an iPad air 2 on 16.2 and it works flawlessly.

**Comment by Lurkars** [comment]
Yes, I think sadly there is nothing I can do here.

**Comment by mherodev** [comment]
Thanks for considering it anyway! We'll just have to get a newer iPad 😅

**Comment by blacksky666666** [comment]
Hi. I bought a mid 2013 build iMac, so NOT an iPad but still had some issues.
I got it to work in chrome then I bricked chrome because I tried to sync it (or something) and would unexpectedly quit everytime I loaded chrome.

So I had to uninstall chrome (including the support files which I don't recall how to find and I can't find the webpage now, but it involved typing in the file manually in 'go' on the map 'finder' app.  I'm not sure if any of this applies to iPads though.

So then I rebooted in safemode and downloaded & installed chrome again (from an incognito safari page) and that worked!. So my advice is to try and find a safe mode or maybe resetting the pram or some such of the iPad. You may be out of luck, as the developer has pointed out.
