### ISSUE TITLE
Feature toggles for various physical component replacements

### ISSUE THREAD

**Issue by Greven145** [Lurkars/gloomhavensecretariat#198]
First off, this app is not just a good replacement for the original that my party used, it is so much better that yesterday we said at least five time "It does THAT? That's awesome!"

I would love to see feature toggles to disable various bit of functionality, like toggling off the character sheets, the party sheets, etc. My party prefers to do the campaign tracking on paper and use the app for combat, so turning the functionality off means less disruption when we accidentally misclick.

I'm happy to submit some PRs to help if that's welcome.

**Comment by Lurkars** [comment]
Thanks for the feedback. Adding settings for this will be no problem, but to be honest, I am a bit confused, that you really accidentally click there and if so that it's a problem. I really tried to make the whole app more or less look and feel like the original helper and to make all additional feature as much as possible in places to not disrupt common helper functionality.

Since the list of settings is so big anyway, adding options to hide/disable some features won't be a problem. So I will still think about this, but just wanted to asks how often it happen that you click accidently.

**Comment by Greven145** [comment]
We played for 9 hours off and on for three sessions, and at least three people said "Whoa, what's this?" It wasn't a problem or anything, easy enough to drop back to the main UI. From a UX perspective it was just the unexpected effects.

For example, tapping the class icon on the right side of the character bringing up the character sheet was surprising. Another time someone was trying to tap on the fire icon and brought up the party sheet accidentally.

For more context, the four of us are all playing on our phones, so we're working in the small UI mode

**Comment by Lurkars** [comment]
So in [v0.58.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.58.1) I added various "additional gameplay" settings to:

- disable Character AM deck
- disable Character Sheet
- disable Loot Deck
- disable Ally AM deck
- disable Party Sheet
- disable Monsters (like in old helper)

I hope this will work fine for you. Please verify and close issue if satisfied.
