### ISSUE TITLE
Invalid shield values on stat card

### ISSUE THREAD

**Issue by gkaragia** [Lurkars/gloomhavensecretariat#202]
The calculation on x2 on poisoned enemies doesn't work correctly. In the following example, the damage applied should be either 6 if the poison is not taken into account or 8 if the poison is taken into account by the app. However the damage applied is 5. 

I am not sure what the x2 button should do in this case as in general shield is not taken into account. If it automatically applies the shield, then the actual damage should be 4 while if it does not the damage should be 6?

![php](https://user-images.githubusercontent.com/53191348/230791932-d22f7e6b-7732-4c3a-be31-3d58caa372d5.gif)

On another note (sorry for not raising a separate bug for this), the armor values on the wind demon cards are wrong. It is 4 while it should be 2. The values in the popup and in `data/fh/monster/wind-demon.json` are correct however, so the wrong ones are coming from someplace else.

**Comment by Lurkars** [comment]
The latter is a bug which should be fixed now in [v0.58.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.58.3).

The Poison issue is a misunderstanding of the function. The app is not considering any AM draw, so if you draw a 2x and making 6 damage instead of 3, you should add 6 damage in the menu instead of 3. If you do so, then the poison reminder is just asking: the damage you applied, is that from a 2x? If so add 2 extra damage from poison otherwise 1. So the 6 damage you're talking about are not calculated in anyway, you have to add that manually. And then the app is asking on poison: did that damage come from 2x or not and only adding poison!

**Comment by gkaragia** [comment]
Ah makes sense now! Thought that the x2 button had a different functionality. Tested the number in the cards and they look good!
