### ISSUE TITLE
Settings resetting by themselves

### ISSUE THREAD

**Issue by gkaragia** [Lurkars/gloomhavensecretariat#203]
We had a weird issue today (I don't have any specific steps to reproduce this) that happened many times during our session.

Sometimes the 'Ability Cards' settings would get disabled by itself which caused cards to not get drawn for monsters. We had the 'Sychronize Settings' setting enabled for all clients. Any ideas about what might be causing this? Any remedies for this to stop?

We are thinking to move the ghs-server to a new private server to see if the issue will stop happening.

**Comment by Lurkars** [comment]
So you are hosting yourself? Is the server on latest version? Please provide as much information possible.

**Comment by gkaragia** [comment]
So it wasn't in the latest version. The version of the server was 0.56.0. Other than that there wasn't anything weird that we did.

We have 3 people running from their phones. These have saved the app on their phone, although they have opened it in the browser at least initially. Some of them have saved the app at least a week ago but one of them just installed it today. Is the app updated automatically when it is saved in the phone?

We also have 1 laptop. From the laptop, I usually go to https://gloomhaven-secretariat.de/ to get served the app and then I just connect to our private server. I have also opened the app and connected to our private server from a PC in the past.

As far as using the app goes, we didn't do any weird steps. The first time it happened we all enabled the `Sychronize Settings' setting but it didn't make things better as it still happened again after a while.

**Comment by Lurkars** [comment]
Okay, server v0.56.0 did not have the ability settings. So please always use latest server with latest client! The app itself should update automatically, but can happen in background and require restart. So may check versions before start. The server versions are always in sync with client version with the following:
server supports client between it's version and next server version, so server v0.56.0 supports client versions >= v0.56.0 < v0.57.7 (because v0.57.7 is next server release!) Besides most servers should also supports clients < server version, it's not 100% guaranteed, but in general you should be more save with a latest server and outdated client then otherwise.

**Comment by gkaragia** [comment]
Ah, this makes sense actually. I would expect that if the server didn't support the setting then each time a sync would happen the local settings would get overwritten and the ability setting would be disabled.

Thank you for the response we will keep this in mind from now on.
