### ISSUE TITLE
Dynamic height for monster ability cards

### ISSUE THREAD

**Issue by z-m-k** [Lurkars/gloomhavensecretariat#205]
Can monster ability cards have variable/dynamic height? Right now, with the fixed height, parts of the ability might not be visible if the zoom is adjusted. This is not solved by the existing ability to scroll the card, as sometimes the card is cut off such that there is no indication that we do not see the full card.

**Comment by Lurkars** [comment]
I think this will be complicated or not look well. The "full ability" setting is already stretching the stats cards to it's limits I would say. So maybe a better solution is to try to determine scrollbar and then try to shrink text. (Then add setting to disable this and add indicator that ability is scrollable)

**Comment by z-m-k** [comment]
Shrinking text defeats the purpose. The issue is that the ability cards can be too small for everyone to see them well.

I was thinking of replacing `monster-ability-front.png` with `monster-ability-front-top.png` and `monster-ability-front-bottom.png`. Where the `bottom` is a background of the parent div and where the `top` has a slight gradient on the bottom edge and is the background of a child div.

I don't think slight artifacting on the transition looks that terrible:
![image](https://user-images.githubusercontent.com/3216223/230952474-f6f41613-5b82-4abe-b37c-631eab16ca07.png)

Top with gradient transparency:
![monster-ability-front-top](https://user-images.githubusercontent.com/3216223/230952534-4acba32d-1e0f-412d-9326-3c199e91862a.png)

Bottom:
![monster-ability-front-bottom](https://user-images.githubusercontent.com/3216223/230952532-9c0aa27d-563e-459c-a3c2-39d7a5078a18.png)

**Comment by Lurkars** [comment]
Not that bad idea, but I am still struggling with the adjustment of the stat card. Any good ideas for that? Because with the "full ability" option, I already had higher ability cards and extra added stretching the stat card, because keeping it same height as before looked more shitty then this little stretching. But stretching too much also doesn't look good, so some similar repeatable design like for the ability would be useful. Also if you are able to create those assets, woiuld be awesome if you just out them in a PR (adding those files will be enough). (And not forget to mention, that there are 2 styles: FH and old GH)

**Comment by z-m-k** [comment]
I am happy to create these assets, but I am having problems figuring out what determines the height of the cards right now so it will be hard for me to test if this works like it should. Can you let me know which div/variable fixes the height right now?

**Comment by Lurkars** [comment]
There is actually no fixed height, I use CSS variables for this to support the zoom function. 
```
  width: calc(var(--ghs-unit) * 40);
  height: calc(var(--ghs-unit) * 21.5);
```
for ability card (without setting `show full ability card`!)

where `--ghs-unit: calc(var(--ghs-width) / var(--ghs-factor))`, the `--ghs-factor: 100` is default and only changes on "zoom-in/out". `--ghs-width` is depending on device width.

Besides, if we want graphics support dynamic height, then the height shouldn't matter.

**Comment by Lurkars** [comment]
In  [v0.76.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.76.0) I added a setting called `Show expanded ability cards` which should solve this issue. Since I wasn't able to get any good looking results, I created the images myself now for also getting no good looking results. So I am happy, if you can take a look at the the new files under `src/assets/images/monster/abilities` and `src/assets/images/fh/monster/abilities`. In the end I am unsure if we really need a repeatable background or if an ability card image with a decent height is enough to cover most cases. Also the backside could also be a sized image or become a repeatable background, since the card flip now just looks a bit strange.

**Comment by Lurkars** [comment]
Did some improvements in [v0.76.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.76.2) and also added a dynamic height to stat cards (only visible in popup-window by now).

**Comment by z-m-k** [comment]
I added the two images for the fronts, both have the same higher resolution background and different tops. I think sizing the back would make it possible to guess what the card is (or is not) before it is revealed. The best solution, I think, would be to animate the flip to the same size div with the larger background with overflow hidden and then do another transition to make the div larger.

**Comment by z-m-k** [comment]
@Lurkars so I misunderstood your previous comment in that I thought you wanted to create a large enough single file that would just be 'the background' that is clipped for smaller cards. Wouldn't that be easier on the css/html front? If you still think that a repeating background is better and you have a solution for that already in place, I'll try to make those files.

As a side note, I think the Gloomhaven background looks better as the current FH background seems like a lower resolution version of the GH (aside from the top banner).

**Comment by Lurkars** [comment]
yeah, it was my intentional thought, that a big one is enough, but thinking about decreasing font-size etc. I think a real repeatable background has benefits and as I already have implementation for it, sounds easier to me. 

And yes, I saw that now the FH style cards has much sharper background but it's the GH style. Have no idea, but of course if possible I would prefer a true FH looking style and not only the head.
