### ISSUE TITLE
Unable to import previous game and/or data exports

### ISSUE THREAD

**Issue by gkaragia** [Lurkars/gloomhavensecretariat#234]
### Overview
I was trying to test a bug that we encountered in our last play session and I am currently not able to load my previous exports. I provide all the exports attached.

### Steps to reproduce
1. Using the public server https://gloomhaven-secretariat.de/ connect using a new game code
2. Try to import the attached data  file
3. For a quick moment it seems like it loads the game session but immediately after the splash screen (in which you select the game) is shown
4. Try to import the attached game file
5. The UI enters into a constant 'Loading' state and nothing works from this point on

[exports.zip](https://github.com/Lurkars/gloomhavensecretariat/files/11240505/exports.zip)

**Comment by Lurkars** [comment]
Game Import should be fixed in [v0.59.11](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.11). Complete data dump will currently not work. Problem is, you import an older state than on server. So this was denied before. I changed this now for import, but not for complete data dump, because too complicated now for a hotfix. If you need to import complete dump, please connect to the server with a new game code and a new game and you should also be able to import.

**Comment by gkaragia** [comment]
Works great now! Thanks!
