### ISSUE TITLE
Potential Bug - Autoscroll on character turn activation brings active character to bottom of screen

### ISSUE THREAD

**Issue by mbpen** [Lurkars/gloomhavensecretariat#258]
Not sure if this is intended behavior, or if there is logic as far as where the autoscrolling will move the newly active character's line. During parts of the session today (0.61.1 on iPad on Safari), clicking the next character to activate their turn would scroll them to the bottom of the display, so all characters/monsters who had already gone in the round were visible. Expected behavior is autoscroll would place newly active character at the top of the display, as at least previously gone characters are less likely to be interacted with vs monsters.

Thank you!

**Comment by Lurkars** [comment]
I think I missfixed this for myself, because in a 2 column layout, scrolling to bottom works better to see the figures on other column. So I think I need to make auto scrolling a lot smarter to check somehow to best view upcoming figures! At least for one column layout, change to top (or center, can also be good to have access to figures before?!) and two column a bit of checking what's best.

**Comment by Lurkars** [comment]
Added some improvements in [v0.62.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.62.0). Please give feedback, thanks.
