### ISSUE TITLE
Feature Request: Blinkblade Time Token Tracker

### ISSUE THREAD

**Issue by datenshi888** [Lurkars/gloomhavensecretariat#264]
With the addition of Fast and Slow for Blinkblade, would it be possible to add a way to keep track of Time Tokens?

The logic for time tokens is as following:
- Always start scenario with 1 Time Token
- Maximum number of Time Tokens is 5
- Declaring Slow for the round awards 1 Time Token, up to a maximum of 2 tokens (ie. declaring Slow while already having two or more tokens does not add a token)
- Declaring Fast uses up a token. Cannot declare Fast if no tokens are available
- Ability Cards can use up or add Time Tokens as part of their actions.

If it's too unreasonable to code an automated way to keep track, would it be possible to give a way to track them manually, say through the conditions window like HP and EXP etc. are modified?

Could visually show the amount of tokens next to the Slow/Fast icons or the name, or maybe next to the HP (ie. just the icon and number of tokens currently)?

**Comment by Lurkars** [comment]
Hey, so the specialized tracking won't cum until I really start implementing support for character ability cards. Because before that, tracking active shield or anything similar will definetly make more sense. But in general, I can think about adding a general token counter on characters, so that would be support for your request to track this manually and will be generalized enough, that I think it could be useful for other classes too. (Tracking any active cars progress etc)

**Comment by Lurkars** [comment]
Hey, so the specialized tracking won't come until I really start implementing support for character ability cards. Because before that, tracking active shield or anything similar will definetly make more sense. But in general, I can think about adding a general token counter on characters, so that would be support for your request to track this manually and will be generalized enough, that I think it could be useful for other classes/functionality too (Tracking any active abilities progress etc).

**Comment by z-m-k** [comment]
Token tracking is also useful for some locked classes, so a general solution would be better.

**Comment by datenshi888** [comment]
Fantastic, thank you! It works great so far!

Something of lesser importance I'd like to mention:

![image](https://user-images.githubusercontent.com/28595867/236570637-90ba4617-0ed4-48e6-9837-68c166d7cf0c.png)

1. Blinkblade can have up to 5 tokens active at a time (unsure about other classes), which can stack with other UI elements (as shown above). Maybe just showing a token and a number of them active at a time would look better? ie [token] x2 or something. Since it's not very common that there would be more than 2 tokens present at a time this is not super important.

2.  This is not really an issue as much as an inconsistency between the physical game and the app. Functionally it makes no difference and it's not really a request to fix it, I just thought I'd bring it up in case somebody cares about it:
Blinkblade time tokens are an additional set of tokens that are visually different from the class ones (they have a hourglass icon instead of the class icon). The class icons are still used for tracking progress on ability cards and items. Again, not something I'd consider worth fixing/implementing two token types just for Blinkblade.

**Comment by Lurkars** [comment]
The suggestion for 1. was already implemented a while ago!
With [v0.66.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.66.0) now came implementation of 2. So special time token for blink blade and some other classes. On BB and matching classes, the special token is the default one to change with dragging, normal token can still be set via. menu!

**Comment by Lurkars** [comment]
Please close this issue if satisfied.
