### ISSUE TITLE
Feature Request: Show number of loots

### ISSUE THREAD

**Issue by keinkurt** [Lurkars/gloomhavensecretariat#293]
Hey Lurkars,

I think it will be very helpful to see the total number of loot tokens, especially for Frosthaven. At least at the scenario summary, but also maybe during the scenario, that you can check the successful finishing of the battle goal Egoist, for example.

Thanks and best regards,
Christian

**Comment by Lurkars** [comment]
Yeah, could make sense. I will think about a good way to show this.

**Comment by Lurkars** [comment]
In [v0.65.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.65.3) I added the total number now in brackets after loot type. I don't add this total number to see anywhere in the scenario, because I think it's wrong, because you don't have knowledge of the total number of resources on that point since you don't know which +1/+2 or enhanced cards are in the deck. I hope it's enough on the summary. Please take a look and close issue if satisfied with result.

**Comment by keinkurt** [comment]
Hey Lurkars, thanks for your work. This is not what we want to have, but maybe this information you build in the summary is helpful for someone else. We want to see the drawn loot cards by character. But now I had seen, that you can click on the loot icon at the character and see the drawn loot card. This is exactly what we need. So, this issue can close.
