### ISSUE TITLE
Frosthaven Scenario 23 missing reward

### ISSUE THREAD

**Issue by odgregg** [Lurkars/gloomhavensecretariat#311]
On completion of Scenario 23 you are meant to obtain a random item blueprint. I did not on completion and had add one manually.

**Comment by TheSquinter** [comment]
Must be a recent bug. Looks like it works on some scenarios (e.g. 18, 19), but not ones which unlock or link to another scenario (e.g. 23, 24, 74).

**Comment by Lurkars** [comment]
So the data is correct, but reward not shown/applied?

**Comment by TheSquinter** [comment]
Yep the data is there:
```
  "rewards": {
    "randomItemBlueprint": 1
  },
```

**Comment by Lurkars** [comment]
Actually not related to linked scenario or so, but `randomItemBlueprint" being the only reward! Should be fixed in [v0.66.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.66.4). Please verify and close issue.

@odgregg : Please notice, this was only a visual a bug, so you gained that random blueprint in GHS anyways it just wasn't shown. So if you add one manually in GHS you may check your item list and remove one of those again.

**Comment by Lurkars** [comment]
> May be a bug when trying to remove unlocked items. Clicking on "Slipper Sword" would remove a different item every time on the first click. Managed to eventually remove it and re add the couple that had been removed. Tried it a couple of times and was doing the same thing on first attempt to remove it.

Actually a bug, should be fixed in [v0.66.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.66.6).

**Comment by odgregg** [comment]
Tested and random blueprint showing up in rewards as expected.
