### ISSUE TITLE
Enemy cards on new scenario

### ISSUE THREAD

**Issue by mqstout** [Lurkars/gloomhavensecretariat#345]
Why when starting a new scenario does it not add ALL enemies the scenario will use to the enemy tracker? It's important when selecting cards (e.g., to pierce if there are shield enemies). It's public information on a scenario setup, and I could swear GHS used to do it.

**Comment by Lurkars** [comment]
Yes, this is in purpose to not spam the screen. And of course I considered that, so after selecting a new scenario,, just open the scenario menu for viewing the "scenario setup"!

![IMG_20230718_070939.jpg](https://github.com/Lurkars/gloomhavensecretariat/assets/2760570/57c96849-08c4-41de-b92e-8c078df8ae31)

(Scenario 1 is bad example, because all monsters are used in first room, but no need to spoiler here, functionality is the same)

**Comment by mqstout** [comment]
Special spoiler monsters (like the early "Sword..." guy) need not be added. Just whichever monster stat cards would be pulled out and set up if a player were going from the scenario setup. It might say "city guard", but if you only do that because you're using the standee for a special boss... city guard appears in play at setup, and special replaces it? becomes its own? I've only looked at the JSON for scenarios a tiny bit, so not sure exactly how it's handled in the data.

[And I personally feel if a boss standee or new standee type ever appears mid-scenario that the setup didn't list, that's a flaw. Spoilers-be-damned. But I'm probably in the minority there. I'm a lso one of those people who wants the full scenario all on one block like it was in GH, and despise the FH sections stuff... But, again, I'm in the minority.]

**Comment by Lurkars** [comment]
So please checkout [v0.68.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.68.5). If this fulfills your need, please close this issue. Thanks.

**Comment by mqstout** [comment]
The option check does as intended. Tested a few known scenarios (Frosthaven 4B & 70 for example) and it worked as expected. Show all stats also is useful for introducing the scenario.
