### ISSUE TITLE
Option to mark treasures when manually concluding a scenario

### ISSUE THREAD

**Issue by mentonin** [Lurkars/gloomhavensecretariat#370]
### Is your feature request related to a problem? Please describe.

When manually "syncing" campaign state to GHS, the workflow is to mark all your scenarios, treasures, and shop states one by one, which can be tiresome

### Describe the solution you'd like

When finishing a scenario from the campaign sheet, show an option to mark scenario treasures as completed, and apply their effects if they unlock items

### Describe alternatives you've considered

A new feature to manually "sync" state could be interesting, too

**Comment by Lurkars** [comment]
General I good idea. To not implement to many dialogs, I think I will add this to the rewards summary. So manually marking a scenario as complete will stay as it is, but when you open rewards, I will add info to show looted treasures too and menu to mark a treasure as looted. 

Small notice for FH: adding toggle for random item loot card too here. Currently no option to mark this manually!

**Comment by Lurkars** [comment]
A general treasure dialog now added in  [v0.77.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.77.2). Just click on the `Treasures` title on the campaign management sheet. If you disable the `multi-select`, you can loot a single treasure with a specific character to apply reward, otherwise the treasures get just added/removed from the list and the rewards are not applied!

Please close this issue if solved. Thanks.
