### ISSUE TITLE
Errata and edition changes information

### ISSUE THREAD

**Issue by mentonin** [Lurkars/gloomhavensecretariat#375]
### Is your feature request related to a problem? Please describe.

The gloomhaven product family is getting old and spanning multiple editions, with many different errata, printings, and editions. When you are playing on old versions, you might not be aware of published errata and clarifications, or may want to play using tweaks from more recent editions. This is already supported on a cross-game scale with custom rules setup (FH rules), but not across editions and errata.

### Describe the solution you'd like

- [ ] A menu where you could select your version and errata/update info you want to apply over it
- [ ] Implementation of all changes that are tracked by the app, such as monster stats
- [ ] Hints on relevant scenarios/sections of which changes were applied (e.g. different monster stats)
- [ ] Hints on relevant scenarios/sections of what changes need to be applied "manually" (e.g. setup position corrections)

### Describe alternatives you've considered

Supporting only a specific version, or multi-version without tweaks. It wouldn't make a big difference most of the time.

Alternatively, adding a feature to lookup scenario/sections within the app could canonicalize the app data.

**Comment by Lurkars** [comment]
I am unsure about this. So first of all in general: I don't see here supporting multiple version of a edition. I would definitely apply all errata on a edition if possible and don't see anyone using wrong rules on purpose. If anyone wants for example a wrong element on a monster's ability, feel free to publish edition data as fan service. Anyway, I see a benefit in the feature of showing errata hints in texts not possible to apply directly in GHS. But that will also be on backlog by now, because I don't see high priority on this.

**Comment by mentonin** [comment]
The most pertinent use case for toggling errata/edition corrections would be for hints. In particular, errata hints that are already corrected in your version of the game can be confusing and annoying.

**Comment by Lurkars** [comment]
So I addressed some stuff here now in [v0.90.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.90.0). I don't think I will work further on this, so I will close the issue afterwards.
So in settings, one can enable `Errata`. Afterwards, the general printing errors are presented as required. It's also stated if this is already applied in GHS (like wrong standees etc.). The other hints should state out, that there is a change/fix to the scenario/section book etc.
