### ISSUE TITLE
Frosthaven: A visible map with stickers updated as you unlock scenarios and upgrade buildings.

### ISSUE THREAD

**Issue by Kafei56** [Lurkars/gloomhavensecretariat#421]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

A visible map would be nice to see our progress through the campaign and for when choosing which scenario to go towards. When you unlock scenarios and buildings/upgrades the map would update alongside with new stickers.

### Describe alternatives you've considered

Currently I'm using (https://gloomhaven-storyline.com/tracker/#/buildings) for this but it would be nice too have it all in one place in my preferred app of Gloomhaven Secretariat.

Thank you for considering!

**Comment by Lurkars** [comment]
You just mean the campaign map right? (Like already implemented for a Gloomhaven campaign, you can take a look at it on the party sheet of a GH campaign).

It's definitely possible and planned, but since there is no data for this directly, I need to handcraft every position for every sticker. So it's just so much work, that I am currently prioritizing other things over this.

I can think about adding like first few stickers for locations and buildings and then request for community help here.

**Comment by Lurkars** [comment]
Btw, as developer it seems I am too stupid, but I can't get any useful interaction with https://gloomhaven-storyline.com/tracker/#/buildings what's the trick? Also I cannot select Frosthaven as edition there.

**Comment by Kafei56** [comment]
Hehe we all have our kryptonite!

If you go to settings on the left, you can enable frosthaven and then it should appear in the drop down menu. With that enabled then the building interface should appear.

**Comment by Kafei56** [comment]
Right and as a simple user I don't know the amount of effort things like this truly take, so no worries really. It's definitely a low priority thing, especially because this functionality exists elsewhere on that gloomhaven storyline website.

Regardless, you rock!

**Comment by Lurkars** [comment]
So in [v0.90.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.90.7) I worked a lot on the map. It's still a ton of work to do, but at least I started and added the overlay stickers too. I also created a debugging helper to drag'n'drop stickers on the map to get the correct position and addressed #432. Still I need to handcraft initial data by now, so **114** scenarios to go here. But wanted to share process.

**Comment by Lurkars** [comment]
So in [v0.90.8](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.90.8) all map sticker and overlays should be in the right place (beside some stuff I don't know about yet and I wont spoiler myself now anymore, because already revealed myself a massive spoiler doing this.)

So happy about feedback here. Besides any bugs, this issue is solved from my side, so please test if possible.

**Comment by Lurkars** [comment]
The spoiler stuff doesn't look that important to me, also one thing missing is the garden building stuff, but that can be covered in different issue (#163). So if you're happy with overall result just close the issue. We can open new ones when some data is wrong etc.
