### ISSUE TITLE
Shackles - Perk

### ISSUE THREAD

**Issue by OZ10** [Lurkars/gloomhavensecretariat#443]
### Describe the bug

When selecting the first checkbox of Pain Conduit's perk 'Increase your maximum hit point value by 5' it removes five hit points. 

### Game Enviroment

Latest 

### To Reproduce

Tick the box, loose hit points. Untick it, then tick it again, loose more points!

### Expected behavior

On the first tick, nothing. Second tick, add five hit points. 

### Gloomhaven Secretariat Version

Can't toggle back to see the version. I refreshed before testing the bug so assume latest. 

### Used Browser

Chrome

### OS

Android

**Comment by Lurkars** [comment]
Ouch, thanks for noticing. Will be fixed in the next 30-60 minutes. I just tested it, and it seems to break the character completely when you max. HP went <= 0. If you want to keep overall progress, notice the current XP value and just toggle the character level to another and back. Then usual max. HP should be restored and character reusable. Afterwards, set XP back to old value (and wait for me to fix!)

**Comment by Lurkars** [comment]
So should be fixed in [v0.82.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.82.1). Happy if you can verify and close issue if solved.

**Comment by OZ10** [comment]
Fixed
