### ISSUE TITLE
Negative conditions not expiring for characters or monsters

### ISSUE THREAD

**Issue by greatguitartist** [Lurkars/gloomhavensecretariat#453]
### Describe the bug

I have set the "Automatically expire conditions" checkbox for the app, but the single turn negative conditions (Immobilize, Stun, Disarm, and Muddle) are not being removed at the end of the next turn.

### Game Enviroment

Game version 0.83.3, scenarios 30, and prior scenarios.
[ghs-settings.json](https://github.com/Lurkars/gloomhavensecretariat/files/13482807/ghs-settings.json)
[ghs-data-dump.json](https://github.com/Lurkars/gloomhavensecretariat/files/13482810/ghs-data-dump.json)

### To Reproduce

1. Draw character initiatives and start round
2. Add a negative condition to a character/monster before or after its turn (Single turn negative condition)
3. After round completes, characters/monsters who had negative condition applied before their turns don't lose the condition
4. At the end of the next round, characters/monsters who had negative conditions applied after their prior turn don't lose the condition.

### Expected behavior

Single turn negative conditions should automatically expire at the end of the character/monster's next turn when the "Automatically expire conditions" checkbox is checked.

### Gloomhaven Secretariat Version

v.0.83.3

### Used Browser

Chrome version 119.0.6045.160 

### OS

Windows 11 64-bit

**Comment by Lurkars** [comment]
I cannot reproduce. There was an issue (#437) prior v0.80.10. Possible that you played on an older version, experienced the issue and just updated afterwards? I am sorry, but it would be really glad if you can retry. I even tested with your data dump and it's working fine for me. The only important thing to notice maybe is the STUN condition, when expired until end of round it is still shown as transparent. This is on purpose, because it can be relevant to remember which standee was stunned in the round and did not act.

**Comment by greatguitartist** [comment]
Restarting the computer seems to have eliminated the issue. Closing ticket
