### ISSUE TITLE
Crossover Character Sheets - Missing Masteries

### ISSUE THREAD

**Issue by obstel** [Lurkars/gloomhavensecretariat#484]
### Edition

Frosthaven

### Type of data

Character Stat/Sheet

### Describe the data affected

Masteries

### Describe the error

Hi Lukars, you closed my other issue regarding the crossover characters, therefore i created a new issue.
The crossover character sheets are missing the masteries:

Example Sun:
https://drive.google.com/drive/folders/1t2VZUGusJWDXTNsq_LKv_zSaD9q3A3Bm

**Comment by Lurkars** [comment]
You must use the Frosthaven Character Sheets to see Masteries etc. This is currently only the case when edition is set to Frosthaven or you manually toggle to the FH sheet on bottom of sheet.

**Comment by obstel** [comment]
But I did that and masteries are missing for gloomhaven characters in my frosthaven campaign.
First I started a frosthaven campaign then activated gloomhaven edition and added Sun afterwards I checked the crossover character option in data management.

On my Sun the masteries are missing.

**Comment by Lurkars** [comment]
Please add the corresponding Crossover Character, not the Gloomhaven one:
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/2760570/de27b80d-4bc6-4146-954b-51dac874e38d)

**Comment by Lurkars** [comment]
If you just setup Frosthaven Campaign and enable Crossover Edition, Character Screen should look like this:
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/2760570/0856741c-aba4-4b39-8948-090adb292224)
without any other edition stuff.

**Comment by obstel** [comment]
Got it thanks, and where can I translate the masteries?

**Comment by Lurkars** [comment]
Currently not possible, will add later today and ping here!

**Comment by obstel** [comment]
Almost done, how should I provide the json?

**Comment by Lurkars** [comment]
Create PR or drop files here or send [email] (mailto:github@gloomhaven-secretariat.de)

**Comment by obstel** [comment]
[de.json](https://github.com/Lurkars/gloomhavensecretariat/files/13833639/de.json)
@Lurkars here you go :) some monster abilities are missing, will finish it tomorrow

**Comment by Lurkars** [comment]
So I moved all character texts now to the corresponding label files. Due to spoiler policy those split into `label/en.json` and `label-spoiler/en.json`. Since there are also a lot of perks or summon actions for characters, I just created the custom label numbered down, so take a look for example at https://github.com/Lurkars/gloomhavensecretariat/blob/main/data/fh/label/en.json#L736 the last two label are mostly the masteries, but may make sense to translate the others too! Hope that helps. I close this issue because it's not related to label and should be solved with my explanations.
