### ISSUE TITLE
Scenario 70 spawn issues

### ISSUE THREAD

**Issue by Jaerin** [Lurkars/gloomhavensecretariat#543]
### Describe the bug

In scenario 70 the special guard in the 3rd section is being added to the UI, but no actual standee is getting spawned.
Also the hounds that are supposed to be spawning did not seem to be spawning either, I'm guessing because we had no boss to do the spawning.

The "boss" in question is the Flaming Sword of Justice

### Game Enviroment

Frosthaven, scenario 70

### To Reproduce

Go to scenario 70
Proceed through to the second section listed
Section 106.2 is the section the mob should spawn with
Flaming Sword of Justice shows up, but no standee is added
No hounds being spawned every round

### Expected behavior

When the mobs are added the Flaming sword of justice standee will be added.  Then every round after that a hound will spawn on point B on the map.

### Gloomhaven Secretariat Version

95.2

### Used Browser

Chrome

### OS

Windows 10

**Comment by Lurkars** [comment]
Besides a bug I introduced a few releases ago, I also notice investigating this, that I don't respect the spawning of elite first before normal monster. So updated this too, otherwise, with 4 player you can also come up in this the scenario to spawn all 6 guard standees and then there is no standee left for the boss. So this is should be fixed now in [v0.95.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.95.5). Happy if you can verify and close issue if solved.

**Comment by Jaerin** [comment]
Tested and working properly!  Thanks for the quick turn around
