### ISSUE TITLE
Adding ranged retaliate to innate melee retaliate on monster ability cards stacking incorrectly.

### ISSUE THREAD

**Issue by Kafei56** [Lurkars/gloomhavensecretariat#556]
### Describe the bug

For example on the Bladespinner card "Fire Storm" the "Retaliate 2 range 2" is combining with the innate retaliate 2 and the app is showing retaliate range 4, where it should be showing retaliate range 2 and retaliate 2. They don't combine into one but instead remain separate, so anyone within range 2 does take 4 retaliate but ranged attackers only suffer 2.

### Game Enviroment

This happened in scenario 36.

### To Reproduce

1. Go to combat with bladespinner
2. Click on start round until they draw fire storm

### Expected behavior

Retaliate with different ranges should be on separate lines and not combined.

### Gloomhaven Secretariat Version

v.0.95.14

### Used Browser

Chrome

### OS

W11

**Comment by Lurkars** [comment]
Should be fixed in  [v0.95.15](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.95.15). But disclaimer here: the retaliate from the stats is now not added to card if ranges does not match. 

In general, I would recommend disabling the setting **Add Shield and Retaliate to abilities** and enable **Shield and Retaliate on Standee** instead. Then you get all actual shield/retaliate for every standee considering stun or summon etc.

If this is solved for you, please close issue. Thanks.

**Comment by Kafei56** [comment]
Thank you!
