### ISSUE TITLE
Adding Conclusion for section 157.3 does not work properly

### ISSUE THREAD

**Issue by jason-rvezy** [Lurkars/gloomhavensecretariat#582]
### Describe the bug

When attempting to use the global campaign management to add the conclusion for section 157.3, the resulting scenario unlock is named 'null' and does not actually unlock the scenario it is meant to.

### Game Enviroment

Frosthaven, section book section 157.3 (unlocks scenario 93)

### To Reproduce

1.  Go to main menu and select Campaign/Character Management
2.  Select Global Campaign Management Sheet
3. In text entry field for 'Add Conclusion', enter 157.3
4. Click Add Conclusion

### Expected behavior

Scenario 93 should be unlocked

### Gloomhaven Secretariat Version

v0.99.9

### Used Browser

Firefox 127.0 (64-bit), also tried in Chrome/Android

### OS

Windows 10, also tried on Android

### Additional

Screenshot of observed behaviour: 
![FHS93Bug](https://github.com/Lurkars/gloomhavensecretariat/assets/94849593/b1acec6f-7df6-4017-805f-54c928761433)

Can also upload save backup if helpful.

**Comment by Lurkars** [comment]
Should be fixed in  [v0.99.10](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.99.10). Issue is, that scenario 93 is divided into the two "93 A" and "93 B", so unlock was just technically wrong. If conclusion is already added, then this should be already fine now and working and you have nothing to do. Please close issue, if solved.

**Comment by jason-rvezy** [comment]
Confirmed to be working with v0.99.10.  Adding conclusion 157.3 unlocked scenario 93A and 93B.
