### ISSUE TITLE
other characters also disappear when retiring, and retiring class is locked out

### ISSUE THREAD

**Issue by bilfdoffle** [Lurkars/gloomhavensecretariat#636]
### Describe the bug

[ghs-data-dump_2024-12-16T03_53_51.003Z.json](https://github.com/user-attachments/files/18144298/ghs-data-dump_2024-12-16T03_53_51.003Z.json)

![image](https://github.com/user-attachments/assets/8ed51128-a676-4afc-b829-3d5e03dc9841)

I'm trying to retire shane the cragheart, as he's gotten his 20 bandit, etc, kills. I push him to 20/20 kills, and click set aside (this is quite confusing, would like a retire button). I then get a prompt for cragheart retirement, and when I click 'apply' it also removes dad the spellweaver from play.

![image](https://github.com/user-attachments/assets/2347b839-ebc6-43f8-b6f7-78ddf2867c96)

Also, the cragheart is locked out from the 'add characters' selection, which would prevent me from playing him again. 
![image](https://github.com/user-attachments/assets/9773dbc4-b1bd-41a1-b025-ebf320439699)

### Game Enviroment

was on server 102.5, upgraded to server 104.0. 
using the latest 105.3 of GHS. In between scenarios.

### Expected behavior

I'd like a simple retire button that's available after conditions are met.
Retirement should not remove other characters from the party.
Retirement should allow the retiring character to be picked again.

### Gloomhaven Secretariat Version

105.3

### Used Browser

webapp from chrome

### OS

windows 11, android

**Comment by Lurkars** [comment]
Okay, this is both a Bug and wrong usage.

First to explain the misunderstanding here:
**_Set Character Aside_** is a feature to switching between characters for one player (see related issue: #128). So this is not related to retirement at all. The rules are allowing for a player to create multiple characters, but you can also play one in a scenario, and therefore you can "put the other aside". Since it is still an active character, it is also correct, that you cannot create a new character in this case, because it is still active. If you put a character aside, you can create a new character available assigned to that player. In the global campaign sheet, on player list, there are the character icons of characters aside, if you double click one, the current active character gets aside and the selected one is active again.

Second the bug:
Still not sure why the Spellweaver retires of you apply the dialog, anyways you found a strange combination of dialogs, because setting a character aside while also activating retirement is not meant to happen. Anyways, I think you found more bad UX, because real retirement seemed confusing.

The solution:
I will just change the Retirement UX:
- add a "Retire Character" Button on the sheet
- automatically open Retirement dialog, if all PQ are met
- disable Retire Character Button if not all PQ conditions are met (force retirement with Double Click)

Will ping here, when the solution is implemented, but I think this will help a lot.

**Comment by Lurkars** [comment]
Done in [v0.105.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.105.4). Happy if you can give some feedback here! Thanks.

**Comment by bilfdoffle** [comment]
just updated, and checked with both my gloomhaven and frosthaven campaigns. Very straightforward now, everything works as far as I can tell.

Only minor suggestion would be to prompt to add the events unlocked when unlocking a new character class for gloomhaven, but I only mention it because of the prompt to add the ones from retirement.

Thanks!

**Comment by Lurkars** [comment]
Thanks for the feedback.
Improved the dialog now a bit in [v0.105.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.105.5):
- show unlock events for new character
- draw random scenario/item when already unlocked (same applies for FH rules, and +1 Inspiration rule when out of scenarios/items)
