### ISSUE TITLE
Monster abilities stuck in a loop?

### ISSUE THREAD

**Issue by z-m-k** [Lurkars/gloomhavensecretariat#71]
I have not found a reliable way of reproducing this, but on 3 occasions now we have noticed that monster abilities cards are stuck on a loop with the same ability that should trigger reshuffle appearing many (5+) times in a row. Maybe we had a very bad luck, but maybe there is some corner case?

**Comment by Lurkars** [comment]
Of course from my point of view, I would say, this is really bad luck. Next time, you experience this, maybe you are willing to spoil yourself the other cards (you call also re-shuffle afterwards): by clicking on the ability cards, a popup window comes up where you can reveal all cards. The order of the cards is how they will be drawn, so you can already see what's the next cards are. When all other cards are in a different order then before, then I would really assume, that it's just (bad) luck.

**Comment by Lurkars** [comment]
In any case, if this happen only on a specific scenario, please provide always more details, so I can better try to reproduce stuff like this.

**Comment by z-m-k** [comment]
The last one we had this issue with was Scenario 18, where Giant Serpent was stuck on 684/5. There are two copies of this card and I do admit that I have not checked at the time if it was consistently 684, 685, or a combination of both. But, having them 5 times in a row is lesst than 0.1% likely. Before that it was Scenario 96, where Earth Demon was stuck on card 640; although here I am not 100% sure about the card as it was long time ago, but ex-post we realized that the demons were mostly not moving at throughout the session.

Next time I notice something similar I will do the 'reveal all', but that would not matter for reshuffle cards being stuck.

**Comment by Lurkars** [comment]
I cannot imagine that shuffle function works incorrectly. It then is an issue that shuffle function doesn't get called at all under some circumstances. By now, i have no clue, so if it happen again, maybe send me a data export of your complete state (I added that under feedback -> send issue, that will be several files, but with that it will be possible for me to get exact same application state and hopefully easier to investigate what's going on.)

**Comment by Lurkars** [comment]
Btw: your math is wrong I think, how do you came to 0.1% chance? On every shuffle, the chance is 1/8 to get a certain card first, because the shuffle is not depending on the result before. If you're only looking at the first card of course. So with two of the shuffle cards in every deck, the chance is 2/8 so (1/4) every time to get a shuffle card. So chances are not so bad to have this 5 times in a row. Think of a dice, you may roll 5 times in a row the same number. Doesn't mean the dice is broken. It would be different math, if ALL cards are always the same, then it's `1/8 x 1/7 x 1/6 x ...` and so on. But if you're only looking at the first card and it was even not always the same, but always 684 or 685, the chance for this for every new round is 1/4. So you can really just get bad luck. Anyways, I changed the shuffle function to be sure. But looking at it deeply, I think you just got bad luck and did some wrong assumption if you didn't look up the non revealed cards. I remember a physical shuffle, where I put two blesses random into deck and then shuffle the deck, then first AM draws was: Bless, Bless, 2x... Didn't feel random, but I was 100% sure, I shuffled and even didn't put the two bless together beforehand.

**Comment by Lurkars** [comment]
haha seem's I need to redo the math. At least 1/1000 still isn't also that bad for bad luck. Anyways... I am still pretty sure the shuffling is working, maybe somehow it isn't called. If this cannot be reproduced, I will close this issue.

**Comment by z-m-k** [comment]
I saw the commit you made, I'm happy closing this. If it is a bug that results in the method not being called then you will need a trace. If it happens again and I notice, I'll reopen.
