### ISSUE TITLE
Suggestion: Increment Round Number During Initiative Phase

### ISSUE THREAD

**Issue by mbpen** [Lurkars/gloomhavensecretariat#78]
Currently the round number by the draw/next round button does not increment until after entering all players initiatives and pressing draw. I think it makes more sense to increment the round number after clicking "next round" so that the current round number is displayed when selecting cards for that given round?

Thoughts? And thank you!

**Comment by Lurkars** [comment]
Ah I know what you mean, like you click "Next Round" and it doesn't increment. Then you click "Draw" and it does. But from logical/rules perspective, it should increment after clicking "Next Round". Seems clear, have to check, if there's a technical reason and many special rules stuff depending on actual round number, so it's not a quick change, because can break some stuff, but I will look into it!

**Comment by Lurkars** [comment]
Please check in [v0.48.9](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.42.9) and close issue if solved for you.

**Comment by mbpen** [comment]
Works great, thank you!
