### ISSUE TITLE
Forgotten Circles - 110 - Wrong Enemy Type, Enemy Immunities

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#85]
Finally getting back to 110 after previous chat and I noticed that the scenario loads with normal enemies, and not the named enemies that have special stats. Here's the list of expected named enemies and their normal type:

Sraka The Wise - (named Vermling Shaman)
Selah Naberis - (named Valrath Tracker)
The Steel Lion - (named City Guard)
Uyart lkkuma - Named Savvas Lavaflow)

All the named enemies are available to add from the "Add Monster" list as a workaround, although Uyart Ikkuma and The Steel Lion are the only "Hidden" monsters. They also both still show special immunities that aren't reflected from the game:

![image](https://user-images.githubusercontent.com/175024/214377659-1d860c87-d7fc-44a0-94a0-bc07abb1d945.png)

Thanks for looking!

**Comment by Lurkars** [comment]
Thanks will be fixed. As stated out, the FC room data is not accurate by now, still working on it, but was busy with other stuff.

**Comment by Lurkars** [comment]
Please validate fix in [v0.48.12](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.42.12)

**Comment by itemforty** [comment]
Yep v0.48.12 auto-populates the named enemies, thank you! 

"Sraka The Wise" and "The Steel Lion" still have immunities on their stat cards:

![image](https://user-images.githubusercontent.com/175024/214394788-03b60563-85e0-4d0f-bd29-f9d99df206c2.png)

"Sraka" and "Selah" are still visible from the "Add Monster" list: 

![image](https://user-images.githubusercontent.com/175024/214394196-0836ec04-8291-4b2b-a915-9883b4f70d76.png)

**Comment by Lurkars** [comment]
Over-read those immunity issue, must have been a C&P issue. Anyways, I updated the v0.48.12 tag, so please verify again.

One issue, I just noticed by now is, that I put "count" to 1 for those bosses, which is technically correct, because there's always only 1 standee, but this leads to the case, that the standee number is always `1`. Do you think it is necessary to split this information, like you can still choose a standee number from 1-6 for example, but only add a single standee or do you thinks it's enough anyways, because with only one "City Guard" standee on the map, the real number doesn't matter at all during gameplay?

**Comment by itemforty** [comment]
Yep, verified they are hidden, automatically added, and don't have immunities. Thanks so much!

> One issue, I just noticed by now is, that I put "count" to 1 for those bosses, which is technically correct, because there's always only 1 standee, but this leads to the case, that the standee number is always 1. Do you think it is necessary to split this information, like you can still choose a standee number from 1-6 for example, but only add a single standee or do you thinks it's enough anyways, because with only one "City Guard" standee on the map, the real number doesn't matter at all during gameplay?

Nah no need to overcomplicate it I think. Just as easy to find the #1 standee instead of changing it in the app, and less work for you in the long run. 

Thanks again!
