### ISSUE TITLE
Intermittent Freezing

### ISSUE THREAD

**Issue by mbpen** [Lurkars/gloomhavensecretariat#87]
Recently (Since ~0.48.8, not exact), on rare occasion when scrolling via touch, the app completely freezes. The only fix is closing the page and re-opening. Unfortunately I don't have much more information for hunting this down. _Potentially_ it was happening more often when not swiping directly up and down, but I suspect that is more just finding a pattern in nothing. It may have to do with exactly where on the screen my finger started so the app was trying to apply a drag change in hp/xp/initiative? I have not tracked this however, so that's nothing more than another random guess. Current occurrence rate is subjectively ~1% of scrolling interactions, based on the number of scenarios/occurrences recently. Let me know if there is a way to pull logs or something to send the next time this happens to help in troubleshooting.

**Comment by Lurkars** [comment]
It's really hard to reproduce, but I was able to go in a similar state. It's definitely related to applying drag and the drag state didn't get canceled properly so app hang. I am 99% sure, that I can just remove the part, because it should be relic from my own drag implementation and now moved to hammer.js, so I think it's not necessary to block input (as I did before). So I hope this will be fixed with  [v0.42.13](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.42.13)

**Comment by dfannius** [comment]
This started happening to me a couple of weeks ago (on desktop), maybe 5 or so times per session. I'm playing again on Jan 29 and will report back afterwards if the issue hasn't already been closed by then.

**Comment by Lurkars** [comment]
> This started happening to me a couple of weeks ago (on desktop), maybe 5 or so times per session. I'm playing again on Jan 29 and will report back afterwards if the issue hasn't already been closed by then.

Thanks for also testing. Our group only use Laptop with projector as big screen, so I personally lacking intense mobile testing!

**Comment by mbpen** [comment]
No freezing in 2 scenarios played tonight on 0.42.17, closing for now.

**Comment by dfannius** [comment]
We also played two scenarios today and experienced no freezing.
