### ISSUE TITLE
Frosthaven scenario 15 spawn timing

### ISSUE THREAD

**Issue by dfannius** [Lurkars/gloomhavensecretariat#94]
The scenario rules say that Ruined Machines spawn at the beginning of every even-numbered round, but according to the app they spawn at the end of every even-numbered round (or at the beginning of every odd-numbered round starting with round 3).

**Comment by Lurkars** [comment]
Thanks, forgot to set the rule to "start of round". Will be fixed. Anyways for information, the Frosthaven Scenario Data is really lacking behind, I am currently working on adding all rules and rooms. To be faster and not switching/searching in section book, I started adding standee data for first rooms of scenarios. But overall, only scenario 0-10 are in a complete state, where real error reporting makes sense. Everything above will be (re-)worked on anyways in the next weeks! I will add this information to the README!

**Comment by Lurkars** [comment]
Please verify fix in [v0.43.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.43.0).

**Comment by dfannius** [comment]
It's better... they spawn near the beginning of the round now, but after the players have set their initiatives and clicked Draw. Ideally they would spawn after Next Round is clicked and before the players set their initiatives.

**Comment by Lurkars** [comment]
Yes, that's the thing that the start of a round is exact the same time as the end of the next round (that confused us so much in JOTL, because it was defined that short rest is decided end of the round and long rest has to be announced start of the round. That's leads us to think, that long rest is only possible with 2 cards left in hand, because otherwise you must short rest beforehand.... In the end, it's just the same time.) Anyways, from current state, this was an explicit design decision for the special rules, that end of round is when clicking next round and start of round when clicking draw. But I am open to change that to the actual timing, where then more rules are shown together.

**Comment by dfannius** [comment]
For our group the sequence is

- a) round 1 is officially over, click Next Round;
- b) round 2 has begun! spawn the new monsters, etc;
- c) discuss our strategy, choose our cards, set our initiatives;
- d) click Draw to find out what the monsters are doing.

So I by the time step d) happens I would already have added the new monsters to the app by hand (and then I would find out that the app was eventually going to do it automatically). In fact in this scenario it actually makes a little difference because (without using the physical cards in the game) we wouldn't know what the base stats on the spawned monsters are until they appear on the app, which we need to know before choosing our cards. I'm not sure if moving start-of-round effects to step b) this would be appropriate for all scenarios but I bet it would be, since I think it always mirrors what we would do without an app.

(And after I wrote that I checked the rules, and on p. 18 they specifically say that start-of-round effects happen at the very start, before card selection.)

**Comment by Lurkars** [comment]
That's what I said, from rules perspective it's totally right, that for example rules say:
- at end of odd round spawn 2 normal monster
- at start of even round spawn 2 elite monster
That when you finish round 1(3,5,..) both messages should show up saying: 
- spawn 2 normal
- spawn 2 elite
because end of round 1 is automatic start of round 2...
So I will change this, because yeah, when shown technically, the time is exact same between end and start, so I thought to not confuse, I will separate those states with start of draw and end of draw, but if taken seriously that's just wrong. I just need to check beforehand if this breaks anything, respectively if I have to adjust some rule data.

**Comment by dfannius** [comment]
Looking at p. 46 of the Frosthaven manual, there are a few things that technically happen between round 1 end-of-round scenario effects and round 2 start-of-round scenario effects: shuffling attack modifier decks, discarding ability cards that lasted until end of round, short rests (like you said, the official timing for this is surprising), element waning. But those all happen instantaneously in the app so I agree that the effect to the player will indeed look identical. (I guess the round number indicator in the bottom bar will say 2 instead of 1 when the dialog comes up.)

**Comment by Lurkars** [comment]
Yes, this could only be solved with three states, like you click "end round", now your "between rounds", then click "next round", now you started the next round, and then click "draw" again. But I thinks that's way confusing, I mean the rules reminder is there, you can do your stuff what ever you want between applying it. The decks are shuffled anyway between those round, those this also happen already "between". I will just change those rules showing up, directly after clicking next round. That's just correct behaviour.

**Comment by dfannius** [comment]
Oh, I don't think there's anything to "solve", especially not at the expense of another user step! It sounds like the behavior you're planning will work great.

**Comment by Lurkars** [comment]
So should be changed now in [v0.43.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.43.1). Please verify.

**Comment by dfannius** [comment]
Looks good to me!
